{

  'Aircraft moved': 1,
  'C177 Time Build': 2,

  'Checkride retraining': 2,

  'Communication, stability': 1,
  'Communications, ADM, Patternwork': 2,

  'Cowling Issue': 1,

  'Cross wind Landings': 3,
  'Cross wind Pattern': 1,
  'Cross wind landings': 6,
  'Crosswind Landing practice': 1,
  'Currency Flight': 4,
  'DME Arc MMM RNAV 1 KSGU': 1,
  'DME Arc, ILS 20 KCDC': 1,
  'DME Holds Airway, Intercept and Track': 1,
  'DP LOC, LDA ': 1,
  'DP RNAV 02, Published Missed, Hold, Arc ILS 20': 1,
  'DP, GPS operation, Holds': 1,
  'DP, RNAV 02': 1,
  'Door open on takeoff': 1,
  'Emergency Landing Eval': 3,
  'Emergency Landing Evaluation': 5,
  'Emergency Landing evaluation': 4,
  'Emergency Procedures': 7,
  'Emergency Procedures Part 1': 2,
  'Emergency Procedures Part 2': 2,
  'Emergency Procedures and Pattern work': 2,
  'Emergency landing eval': 1,
  'Emergency procedures': 5,
  'Emergency procedures Part 1': 1,
  'Emergency procedures part 1': 1,
  'Emergency procedures part 2': 1,
  'Engine failure on Taxi': 1,
  'Flat Tire on Taxi': 1,
  'Flight': 3,
  'Flight Review': 39,
  'Flight Review / Landing Practice': 2,
  'Flight refresher': 1,
  'Flight review': 8,
  'GPS Holds and gusty landing practice': 1,
  'GPS LOC approaches': 1,
  'Ground Referance Manuvers': 8,
  'Ground referance manuvers': 1,
  'High Preformance Nav and Pattern work': 1,
  'High preformance complex training': 1,
  'Hold LDA, Instrument Attitude Flight': 1,
  'Hold Procedures': 1,
  'Hold Procedures LOC, LDA ': 1,
  'Hold Procedures all entries': 1,
  'Hold UTI, RNAV 1 KSGU, CTL': 1,
  'Hold, LDA, LOC, DP': 1,
  'Holding procedures LDA G/S': 1,
  'Holds': 4,
  'Holds / PP': 1,
  'Holds All Entries': 1,
  'Holds Direct Entry': 1,
  'Holds LDA GS 19 KSGU': 1,
  'Holds all entries LDA': 1,
  'Holds, Attitude Instrument Flight': 1,
  'Holds, LDA 19 KSGU PP': 1,
  'Holds, LOC, LDA': 1,
  'Holds, RNAV 01 KSGU CTL 19': 1,
  'Holds, all entries': 1,
  'IFR ACS': 66,
  'IFR Checkride Prep': 1,
  'IFR Communication RNAV 02 67L': 2,
  'IFR Cross country': 2,
  'IFR Cross country Training': 36,
  'IFR Cross country training': 2,
  'IFR Cross country training GPS 12R': 1,
  'IFR Cross country training LDA 19': 1,
  'IFR Cross country training VOR 20': 1,
  'IFR Curency': 1,
  'IFR Procedures ILS,RNAV cross country': 1,
  'IFR Procedures cross country': 1,
  'IFR TRaining': 14,
  'IFR Traing': 2,
  'IFR Training': 150,
  'IFR Xcountry': 1,
  'IFR training': 2,
  'ILS 12L KVGT': 1,
  'ILS 20, RNAV 20, LDA 19': 1,
  'ILS 3 KGCN IFR Cross country Training': 1,
  'ILS, LDA, Communications': 1,
  'ILS,PP,LOC,GPS, Hold , Unusual Attitudes': 1,
  'IPC': 11,
  'IPC Prep': 3,
  'IPC Training': 1,
  'Icing conditions after runup': 2,
  'Instrument ACS': 1,
  'Instrument Approaches': 1,
  'Instrument Attitude Flight': 1,
  'Instrument Checkride Prep': 1,
  'Instrument Training': 7,
  'Instrument attitude flight LDA': 1,
  'Instrument cross country Training': 2,
  'Intro': 1,
  'Intro Flight': 14,
  'Intro flight': 53,
  'LDA': 1,
  'LDA / LOC Approach': 1,
  'LDA 19 G/S': 1,
  'LDA 19 G/S Instrument cross country Training': 1,
  'LDA 19 KSGU': 1,
  'LDA 19 KSGU Hold UTI': 1,
  'LDA 19 KSGU PP': 1,
  'LDA 19, Holds, DP, LOC19': 1,
  'LDA 19, LOC19, RNAV 1, U/A': 1,
  'LDA Attitude Instrument Flight': 1,
  'LDA G/S 19': 1,
  'LDA G/S 19 LOC 19': 1,
  'LDA G/S 19 RNAV 19': 1,
  'LDA G/S Hold Direct entry': 1,
  'LDA G/S, LDA PP, Hold': 1,
  'LDA G/S, LDA PP, RNAV, Hold': 2,
  'LDA LOC': 2,
  'LDA, LOC 19 KSGU': 1,
  'LOC, LDA Approaches': 1,
  'Landing Evaluation': 1,
  'Landing Practice': 1,
  'Local ATC': 2,
  'Local senic flight': 1,
  'Mag issue': 1,
  'Manuvers and Pattern work': 2,
  'Navigation Training': 2,
  'New Student Evaluation': 3,
  'Night Cross country': 5,
  'Night Cross country Training': 8,
  'Night Cross country training': 4,
  'Night Currency Flight': 2,
  'Night Flight': 1,
  'Night Flight Training': 2,
  'Night Landings': 9,
  'Night Operations, Pattern work': 1,
  'Night Pattern work': 1,
  'Night Training': 2,
  'Night X Country': 1,
  'Night landings': 1,
  'Non Precision approach procedures': 1,
  'Nose Strut issue': 1,
  'Oil pressure issue': 1,
  'PA 24 Checkout': 1,
  'PA 24 Training': 3,
  'PA 24 traing': 1,
  'PA 24-250 intro': 1,
  'PA24 Checkout': 1,
  'PA24 Intro': 1,
  'PA24 Training': 3,
  'PA44 cross country': 4,
  'Pattern Work': 3,
  'Pattern work': 288,
  'Pattern work / Flight review': 1,
  'Pattern work / Trim Flight': 1,
  'Pattern work and Steep Turns': 1,
  'Pattern work and Visual attitude flight': 1,
  'Pattern work and manuvers': 1,
  'Pattern work crosswind Landings': 1,
  'Pattern work part 3': 1,
  'Pattern work part 4': 1,
  'Pattern work part 4,5': 1,
  'Pattern work part 5': 1,
  'Pattern work part 6': 1,
  'Pattern work, Engine out': 1,
  'Pattern work, Forward Slip, Ground Referance': 1,
  'Pattern work, Stalls, Emergency Decent': 1,
  'Pattern work, Unusual attitudes': 1,
  'Pattern wotk': 1,
  'Power on/off stalls, soft/short field landings': 1,
  'Pre Solo Training': 2,
  'Pre Solo warm up': 1,
  'Pre solo Landing Evaluation': 1,
  'Pre solo Training': 13,
  'Pre solo evaluation': 5,
  'Pre solo flight training': 1,
  'Pre solo training': 58,
  'Pre solo training, Low approaches, Visual Attitude Flight': 1,
  'Pre solo warm up': 1,
  'Presolo Training': 18,
  'Presolo Traning': 4,
  'Presolo manuvers': 1,
  'Presolo training': 6,
  'Presolo training, visual attitude flight': 1,
  'Pricision and Non Precision Approaches': 2,
  'Private ACS': 41,
  'Private ACS Landings': 1,
  'Private Pilot ACS': 109,
  'Private Pilot ACS Landings': 2,
  'Private Pilot Check ride Training': 1,
  'Private Pilot Checkride Prep': 6,
  'Private Pilot Lesson 1.1': 2,
  'Private Pilot Lesson 1.2': 2,
  'Private Pilot Lesson 1.3': 1,
  'Private Pilot Lesson 2.3': 1,
  'Private Pilot Manuvers': 6,
  'Private Pilot Stalls and Pattern work': 1,
  'Private Pilot Training': 6,
  'Private Pilot manuvers': 2,
  'Private pilot checkride Prep': 1,
  'Procedure Turns, Arc,': 1,
  'Proficency Flight': 3,
  'RNAV 01, IFR Communication': 2,
  'RNAV 01, RNAV 19 KSGU': 1,
  'RNAV 1 KSGU': 1,
  'RNAV 1 KSGU IFR Cross country Training': 1,
  'RNAV 12R ILS 12L KVGT': 1,
  'RNAV 33 Instrument cross country Training': 1,
  'Recreational Pilot Manuvers': 1,
  'Recreational Pilot PTS': 85,
  'Reorentation Flight': 1,
  'Review Flight': 2,
  'Review flight': 1,
  'Run up failure': 1,
  'Safty Pilot': 7,
  'Search for Hourse': 1,
  'Simulated Hood Time': 1,
  'Simulated Instrument Training': 1,
  'Slow Flight and Stalls': 4,
  'Slow flight and Stalls': 3,
  'Slow flight and stalls': 2,
  'Slow flight, Stalls,': 1,
  'Slow flight, Stalls, Seep Turns and Landings': 1,
  'Solo Evaluation': 8,
  'Solo Landing Eval': 2,
  'Solo Landing Evaluation': 4,
  'Solo Landing evaluation': 2,
  'Solo Warm up': 4,
  'Solo Warmup': 1,
  'Solo warm up': 20,
  'Stability and Landing practice': 1,
  'Stall Training': 2,
  'Stall lesson 1.4': 1,
  'Stall lesson 1.5': 1,
  'Stalls and Pattern work': 1,
  'Stalls and Slow flight': 2,
  'Static Failure': 1,
  'Tach Issue': 1,
  'Test Flight': 1,
  'Test flight': 3,
  'Throttle issue on taxi': 1,
  'Training': 1,
  'Transport': 2,
  'Troubleshoot and Pattern work': 1,
  'VOR Approach, Attitude instrument flight': 1,
  'VOR Approaches': 2,
  'VOR B KPGA IFR Cross country Training': 1,
  'VOR Holds': 1,
  'VOR Intro': 1,
  'VOR Navigation and Pattern work': 1,
  'VOR Navigation and approaches': 1,
  'VOR Track and Holds': 2,
  'VOR Track, Heading, RNAV 19 KSGU': 1,
  'VOR Tracking and Intercept': 1,
  'VOR, ILS 20 KCDC': 1,

  'WINGS Flight A100126-54': 1,
  'Weather issue during Taxi,': 1
}