import React from 'react'
// C:\Users\Butter\Documents\GitHub\DareToDream\dtd\src\modules\timeline\timeline_flight.jsx
import TimelineFlight from '../timeline/timeline_flight'

function Timeline() {

    let timeline_data = [
        {
            Template: 'TimelineFlight',
            FlightNumber: '1',
            Date: '2009-11-18',
            AirplaneModel: 'PA28-140',
            TailNumber: 'N55634',
            Departure: 'KVGT',
            DepartureName: 'North Las Vegas',
            Arrival: 'Local',
            ArrivalName: 'Local',
            Hours: '1.2',
            Memo: 'PPL Manuvers ',
            Caption: 'First Flight',
            BottomSpacing: '100vh'
            // Two other flights in 2009
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '4',
            Date: '2012-04-18',
            AirplaneModel: 'C172',
            TailNumber: 'N9387H',
            Departure: 'KVGT',
            DepartureName: 'North Las Vegas',
            Arrival: 'Local',
            ArrivalName: 'Local',
            Hours: '2.0',
            Memo: 'Taxi Takoff, Stalls, Manuvers',
            Caption: 'Started Flight School',
            BottomSpacing: '100vh'
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '29',
            Date: '2012-07-16',
            AirplaneModel: 'C172',
            TailNumber: 'N623SP',
            Departure: 'KVGT',
            DepartureName: 'North Las Vegas',
            Arrival: 'Local',
            ArrivalName: 'Local',
            Hours: '2.4',
            Memo: 'Solo warm up and First Solo',
            Caption: '\'First\' Solo',
            BottomSpacing: '10px'
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '30',
            Date: '2012-07-18',
            AirplaneModel: 'C172',
            TailNumber: 'N623SP',
            DepartureName: 'North Las Vegas',
            Departure: 'KVGT',
            Arrival: '67L',
            ArrivalName: 'Mesquite',
            Hours: '3.4',
            Memo: 'Cross Country Training',
            Caption: 'First Cross Country',
            BottomSpacing: '100vh'
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '35',
            Date: '2012-09-14',
            AirplaneModel: 'C172',
            TailNumber: 'N635SP',
            Departure: 'KVGT',
            DepartureName: 'North Las Vegas',
            Arrival: 'KSGU',
            ArrivalName: 'St. George',
            Hours: '3.7',
            Memo: 'Night Flight Training',
            Caption: 'Night Flight!',
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '58',
            Date: '2013-02-05',
            AirplaneModel: 'C172',
            TailNumber: 'N65842',
            Departure: 'KVGT',
            DepartureName: 'North Las Vegas',
            Arrival: '67L',
            ArrivalName: 'Mesquite',
            Hours: '3.2',
            Memo: 'Solo Cross Country',
            Caption: 'First Solo Cross Country',
            BottomSpacing: '100vh'
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '63',
            Date: '2013-02-27',
            AirplaneModel: 'C172',
            TailNumber: 'N7723G',
            Departure: 'KVGT',
            DepartureName: 'North Las Vegas',
            Arrival: '0L7',
            ArrivalName: 'Jean',
            Hours: '2.2',
            Memo: 'Private Pilot Check Ride - Pass',
            Caption: '\'Offical\' (Checkride 1/7)',
            BottomSpacing: '100vh'
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '75',
            Date: '2013-04-23',
            AirplaneModel: 'PA44-180',
            TailNumber: 'N573AT',
            Departure: 'KVGT',
            DepartureName: 'North Las Vegas',
            Arrival: 'Local',
            ArrivalName: 'Local',
            Hours: '1.6',
            Memo: 'Multi Engine Manuvers',
            Caption: 'Multi Engine Training',
            BottomSpacing: '100vh'
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '81',
            Date: '2013-05-27',
            AirplaneModel: 'PA44-180',
            TailNumber: 'N746A',
            Departure: 'KVGT',
            DepartureName: 'North Las Vegas',
            Arrival: 'Local',
            ArrivalName: 'Local',
            Hours: '1.3',
            Memo: 'MEL Checkride Pass',
            Caption: 'Checkride 2/7',
            BottomSpacing: '0px'
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '121',
            Date: '2013-10-23',
            AirplaneModel: 'PA44-180',
            TailNumber: 'N574AT',
            Departure: 'KVGT',
            DepartureName: 'North Las Vegas',
            Arrival: 'Local',
            ArrivalName: 'Local',
            Hours: '1.5',
            Memo: 'Instrument Check Ride - Pass',
            Caption: 'Checkride 3/7',
            BottomSpacing: '100vh'
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '141',
            Date: '2014-01-17',
            AirplaneModel: 'PA44-180',
            TailNumber: 'N910KT',
            Departure: 'KVGT',
            DepartureName: 'North Las Vegas',
            Arrival: 'Local',
            ArrivalName: 'Local',
            Hours: '1.6',
            Memo: 'Commerical MEL Checkride - Pass',
            Caption: 'Checkride 4/7',
            BottomSpacing: '0px'
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '148',
            Date: '2014-02-21',
            AirplaneModel: 'PA44-180',
            TailNumber: 'N574AT',
            Departure: 'KVGT',
            DepartureName: 'North Las Vegas',
            Arrival: 'Local',
            ArrivalName: 'Local',
            Hours: '1.3',
            Memo: 'MEI Checkride - Pass',
            Caption: 'Checkride 5/7',
            BottomSpacing: '100vh'
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '151',
            Date: '2014-03-14',
            AirplaneModel: 'PA44-180',
            TailNumber: 'N766A',
            Departure: 'KVGT',
            DepartureName: 'North Las Vegas',
            Arrival: 'Local',
            ArrivalName: 'Local',
            Hours: '1.1',
            Memo: 'CFII Checkride Pass',
            Caption: 'Checkride 6/7',
            BottomSpacing: '100vh'
        },
        // {
        //     Template: 'TimelineFlight',
        //     FlightNumber: '157',
        //     Date: '2014-04-07',
        //     AirplaneModel: 'C150',
        //     TailNumber: 'N3073S',
        //     Departure: '67L',
        //     DepartureName: 'Mesquite',
        //     Arrival: 'KIGM',
        //     ArrivalName: 'Kingman',
        //     Hours: '1.5',
        //     Memo: 'Flight for friend',
        //     Caption: '',
        //     BottomSpacing: '10px'
        // },
        {
            Template: 'TimelineFlight',
            FlightNumber: '176',
            Date: '2014-07-08',
            AirplaneModel: 'C150',
            TailNumber: 'N3073S',
            Departure: 'KVGT',
            DepartureName: 'North Las Vegas',
            Arrival: 'Local',
            ArrivalName: 'Local',
            Hours: '1.0',
            Memo: 'COM SEL Checkride - Pass',
            Caption: 'Checkride 7/7',
            BottomSpacing: '10px'
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '177',
            Date: '2014-07-08',
            AirplaneModel: 'C150',
            TailNumber: 'N3073S',
            Departure: 'KVGT',
            DepartureName: 'North Las Vegas',
            Arrival: 'Local',
            ArrivalName: 'Local',
            Hours: '1.1',
            Memo: 'CFI SEL Checkride - Pass',
            Caption: 'Offical CFI',
            BottomSpacing: '100vh'
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '179',
            Date: '2014-08-12',
            AirplaneModel: 'C150',
            TailNumber: 'N3073S',
            Departure: '67L',
            DepartureName: 'Mesquite',
            Arrival: 'Local',
            ArrivalName: 'Local',
            Hours: '0.7',
            Memo: 'Intro Flight with Mikian Musser',
            Caption: 'First Student',
            BottomSpacing: '10px'
            // First instruction given
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '180',
            Date: '2014-08-13',
            AirplaneModel: 'C150',
            TailNumber: 'N3073S',
            Departure: '67L',
            DepartureName: 'Mesquite',
            Arrival: 'Local',
            ArrivalName: 'Local',
            Hours: '0.6',
            Memo: 'Intro Flight with Mira Larson',
            Caption: 'Flight with Mira',
            BottomSpacing: '100vh'
        },
        // {
        //     Template: 'TimelineFlight',
        //     FlightNumber: '210',
        //     Date: '2015-02-27',
        //     AirplaneModel: 'C150',
        //     TailNumber: 'N3073S',
        //     Departure: 'U08',
        //     DepartureName: 'Overton',
        //     Arrival: 'Local',
        //     ArrivalName: 'Local',
        //     Hours: '1.2',
        //     Memo: 'Search for Hourse With Hinds',
        //     Caption: '',
        //     BottomSpacing: '10px'
        // },
        {
            Template: 'TimelineFlight',
            FlightNumber: '478',
            Date: '2019-03-16',
            AirplaneModel: 'C172',
            TailNumber: 'N5225D',
            Departure: 'KSGU',
            DepartureName: 'St. George',
            Arrival: 'Local',
            ArrivalName: 'Local',
            Hours: '1.3',
            Memo: 'Intro flight with Nevaeh Musser',
            Caption: 'Flight with Nevaeh',
            BottomSpacing: '10px'
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '641',
            Date: '2020-01-04',
            AirplaneModel: 'C172',
            TailNumber: 'N5378D',
            Departure: 'KSGU',
            DepartureName: 'St. George',
            Arrival: 'Local',
            ArrivalName: 'Local',
            Hours: '2.0',
            Memo: 'Flight with Jacob Musser',
            Caption: 'Flight with Jacob',
            BottomSpacing: '100vh'
        },
        {
            Template: 'TimelineFlight',
            FlightNumber: '956',
            Date: '2021-10-03',
            AirplaneModel: 'C172',
            TailNumber: 'N5225D',
            Departure: 'KSGU',
            DepartureName: 'St. George',
            Arrival: 'Local',
            ArrivalName: 'Local',
            Hours: '1.9',
            Memo: 'Intro flight with Abagail Musser',
            Caption: '',
            BottomSpacing: '100vh'
        },
    ]

    return (
        <>
            {timeline_data.map((item, index) => {
                return (
                    <div key={index} className="h-screen w-full">
                        {item.Template === 'TimelineFlight' && <TimelineFlight flight={item} />}
                    </div>
                )
            })}
        </>
    )
}

export default Timeline
