dtd_config = {
    'data_path': 'data/source/raw_flight_data.csv',
    'output_folder': 'data/output/',
    'passenger_name_consolidation': {
        'Adam Berger': [
            'Adam Berger',
            'Adam Burger'
        ],
        'Bruce Roden': [
            'Bruce Roden',
            'Bruse Roden'
        ],
        'Chris Frainer': [
            'Chris Frainer',
            'Chris Frchner'
        ],
        'Clair Christanson': [
            'Clair Christanson',
            'Clair Christenson',
            'Clair Christianson',
        ],
        'Conner Dockstader': [
            'Conner Dockstader',
            'Conner',
        ],
        'Cris Atkins': [
            'Cris Atkins',
            'Cris',
        ],
        'Ed Lewis': [
            'Ed Lewis',
            'Ed Lewis LDA 19 G',
        ],
        'Curtis Witwer': [
            'Curtis Witwer',
            'Curtis Wittwer',
        ],
        'David Peterson': [
            'David Peterson',
            'David Petersen',
            'Dave Petterson',
            'David Paterson',
        ],
        'Dillon Erickson': [
            'Dillan Errickson',
            'Dilllon Errickson',
            'Dillon Erickson',
            'Dillon Errickson',
        ],
        'Doug Clauser': [
            'Doug Clauser',
            'Doug Clavser',
        ],
        'Greg Krahenbuhl': [
            'Greg Krahenbuhl',
            'Greg K',
        ],
        'Hinds': [
            'Hourse With',
        ],
        'Isaah Fairchild': [
            'Isaah Fairchild',
            'Issah Fairchild',
        ],
        'James Matson': [
            'James Matson',
            'James Motson',
        ],
        'Jim Bueto': [
            'Jim Bueto',
            'Jim Buteo',
            'Jim Buto',
        ],
        'Jorden Taylor': [
            'Jorden Taylor',
            'Jordan Taylor',
        ],
        'Josh Sorenson': [
            'Josh Sorenson',
            'Josh',
        ],
        'Kevin LeBaron': [
            'Kevin LeBaron',
            'Kevin Lebaron',
            'Kevin Labaron',
            'Keven Lebaron',
            'Keven LeBaron',
            'Kalvin Lebaron',
        ],
        'Koby Hughes': [
            'Koby Hughes',
            'Kody Hughes',
        ],
        'Lance Shear': [
            'Lance Shear',
            'Lance S',
            'Lance',
        ],
        'Logan Otoole': [
            'Logan Otoole',
            'Logan',
        ],
        'Max Macdonald': [
            'Max',
            'Max Macdonald',
            'Max Mcdonald',
        ],
        'Mitchell Rabb': [
            'Mitchel Raab',
            'Mitchel Rabb',
            'Mitchell Raab',
            'Mitchell Rabb',
        ],
        'Montsettet': [
            'Monserret',
            'Montsettet',
        ],
        'Brian Mann': [
            'Brian Mann',
            'Bryan Mann',
        ],
        'Nick Mann': [
            'Nick Mahan',
            'Nick Mann',
        ],
        'Paul Dal\'s son': [
            'Paul Dal\'s',
        ],
        'Rebecca Allred': [
            'Rebecca Allred',
            'Rebecca',
        ],
        'Richard Paine': [
            'Richard Paine',
            'Richard Pinie',
        ],
        'Rick Casebolt': [
            'Rick Casbolt',
            'Rick Casebolt',
        ],
        'Ricky Kasper': [
            'Rick Kasper',
            'Ricky Kasper',
        ],
        'Savannah Milton': [
            'Savanah Milton',
            'Savannah Milton',
        ],
        'Tracy Acord': [
            'Tracy Accord',
            'Tracy Acord',
        ],
        'Trendon Delray': [
            'Trendon Daley',
            'Trendon Delray',
        ],
        'Trent Sonderegger': [
            'Trent S',
            'Trent Sonderegger',
        ],
        'Tyson Teerlink': [
            'Tyson',
            'Tyson Teerlink',
        ],
    },
    'flight_objective_consolidation': {
        'Maneuvers': [
            'PPL Manuvers ',
            'AC11 Manuvers',
            'Basic manuvers',
            'Ground Referance Manuvers',
            'Ground referance manuvers',
            'Manuvers, Landings',
        ],
        'ATC Training': [
            'ATC Autopilot Nav Training',
            'ATC IFR Procedures',
            'ATC IFR Procedures LDA 19 G/S',
            'ATC IFR, DP,LDA,LOC',
            'ATC Intro',
            'ATC Pattern work',  
            'ATC training',
        ],
        'Attitude Instrument Flight': [
            'Attitude Instrument Flight'
            'Attitude Instrument Flight / IFR Cross country procedures'
            'Attitude Instrument Flight / UA Recovery'
            'Attitude Instrument Flight, LDA G/S'
        ],
        'Flight Review':[
            'BFR',
            'Flight',
            'Flight Review',
            'Flight Review / Landing Practice',
            'Flight refresher',
            'Flight review',
            'Review Flight',
            'Review flight',
            'Flight Review By Rachel Adams',
            'Flight Review and C172 Checkout',
            'Flight Review, Given by Dakota Bair',
        ],
        'Aircraft Training': [
            'C15 Training',
            'C177 Training',
            'C210 Training',
        ],
        'Checkout': [
            'C150 Checkout',
            'C152 Checkout',
            'C172 Check out',
            'C172 Checkout',
            'C172 Intro / Checkout',
            'PA 24 Checkout',
            'PA24 Checkout',
            'Archer Checkout',
            'Checkout Flight',
            'Checkout flight',
            'Archer Checkout',
            'Checkout',
            'Checkout Flight',
            'Checkout flight',
            'C172XP Checkout',
            'C177 Checkout by Cris Atkens',
            'Grimes Checkout',
            'High preformance check out',
        ],
        'CFI Training': [
            'CFI PTS',
            'CFI PTS Landings',
            'CFI Training',
            'CFII ACS',
            'CFII Training',
            'CFI Manuvers',
            'CFI SEL Prep',
        ],
        'Visual Attitude Flight': [
            'Visual Attitude Trim Flight',
            'Visual Attitude trim Flight Lesson 1.1',
            'Visual Attitude trim flight',
            'Visual Attitude Flight',
            'Visual Attitude and Pattern work',
            'Visual Attitude flight',
            'Visual attatude Flight',
            'Visual attitude Flight',
            'Visual attitude flight',
            'Visual attitude flight, Pattern work',
            'Attitude Trim flight',
        ],
        'Cross Country': [
            'Solo Cross Country',
            'Commerical Cross country',
            'Commerical Crosscountry',
            'Commerical cross country',
            'Commerical crosscountry training',
            'Cross Country',
            'Cross Country Training',
            'Cross Country Treaning',
            'Cross Country evaluation',
            'Cross Country procedures Intro',
            'Cross Country training',
            'Cross country',
            'Cross country ATC',
            'Cross country C177 flight',
            'Cross country Evaluation',
            'Cross country Traing',
            'Cross country Training',
            'Cross country evaluation',
            'Cross country procedures',
            'Cross country training',
            'Criss country Training',
            'Night Cross country',
            'Night Cross country Training',
            'Night Cross country training',
            'Night X Country',
            'X Country to St Geroge',
            'PA44 cross country',
        ],
        'Night Training': [
            'Night Training',
            'Night landings',
            'Night Landings',
            'Night Currency Flight',
            'Night Flight',
            'Night Flight Training',
        ],
        'Private Pilot Training': [
            'Private ACS',
            'Private ACS Landings',
            'Private Pilot ACS',
            'Private Pilot ACS Landings',
            'Private Pilot Check ride Training',
            'Private Pilot Lesson 1.1',
            'Private Pilot Lesson 1.2',
            'Private Pilot Lesson 1.3',
            'Private Pilot Lesson 2.3',
            'Private Pilot Manuvers',
            'Private Pilot Stalls and Pattern work',
            'Private Pilot Training',
            'Private Pilot manuvers',
        ],
        'Commercial Training': [
            'COM ACS',
            'COMmerical ACS',
            'Commerical ACS',
            'COM Landings',
            'COM Manuvers',
            'COM landings',
            'COM manuvers',
            'Commerical Manuvers',
            'Commerical Manuvers and Landings',
            'Commerical Towered Landings at night',
            'Commerical manuvers',
            'COM Check Ride prep',
            'COM Crew Training',
            'COM Cross Country',
            'COM Manuvers and Landings',
        ],
        'Intro Flight': [
            'C177 Intro',
            'C172 Orentation',
            'Intro',
            'Intro Flight',
            'Intro flight',
            'Intro flight aborted Take off',
            'New Student Evaluation',
            'PA 24-250 intro',
            'PA24 Intro',
        ],
        'Instrument Training': [
            'Instrument ACS',
            'Instrument Approaches',
            'Instrument Attitude Flight',
            'Instrument Training',
            'ILS 20 Arc VOR 20 LDA 19',
            'LOC ILS GPS',
            'ILS GPS',
            'ILS 12L KVGT',
            'DP ILS',
            'ILS 20, RNAV 20, LDA 19',
            'ILS 3 KGCN IFR Cross country Training',
            'ILS, LDA, Communications',
            'ILS,PP,LOC,GPS, Hold , Unusual Attitudes',
            'Instrument attitude flight LDA',
            'Instrument cross country Training',
            'Attitude Instrument Flight',
            'Attitude Instrument Flight / IFR Cross country procedures',
            'Attitude Instrument Flight / UA Recovery',
            'Attitude Instrument Flight, LDA G/S',
        ],
        'IPC': [
            'IPC',
            'IPC Prep',
            'IPC Training',
        ],
        'LDA': [
            'LDA 19, LOC 19, RNAV 1,HOLD VOR U/A IPC by Kaden Staley',
            'LDA G/S 19 LOC 19 RNAV 19, LNAV 19 Safty Pilot Mitchell Rabb',
            'LDA, RNAV 19 KSGU / PP Jonathan Demke Safty Pilot',
            'LDA',
            'LDA / LOC Approach',
            'LDA 19 G/S',
            'LDA 19 G/S Instrument cross country Training',
            'LDA 19 KSGU',
            'LDA 19 KSGU Hold UTI',
            'LDA 19 KSGU PP',
            'LDA 19, Holds, DP, LOC19',
            'LDA 19, LOC19, RNAV 1, U/A',
            'LDA Attitude Instrument Flight',
            'LDA G/S 19',
            'LDA G/S 19 LOC 19',
            'LDA G/S 19 RNAV 19',
            'LDA G/S Hold Direct entry',
            'LDA G/S, LDA PP, Hold',
            'LDA G/S, LDA PP, RNAV, Hold',
            'LDA LOC',
            'LDA, LOC 19 KSGU',
            'LOC, LDA Approaches',
        ],
        'Complex Training': [
            'Complex Pattern work',
            'Complex training',
            'Complex traning',
        ],
        'Pre Solo Training': [
            'Pre Solo Training',
            'Pre Solo warm up',
            'Pre solo Landing Evaluation',
            'Pre solo Training',
            'Pre solo evaluation',
            'Pre solo flight training',
            'Pre solo training',
            'Pre solo training, Low approaches, Visual Attitude Flight',
            'Pre solo warm up',
            'Presolo Training',
            'Presolo Traning',
            'Presolo manuvers',
            'Presolo training',
            'Presolo training, visual attitude flight',
        ],
        'Solo Flights': [
            'Solo warm up and First Solo',
            'Solo at Mesquite',
            'Solo Evaluation',
            'Solo Landing Eval',
            'Solo Landing Evaluation',
            'Solo Landing evaluation',
            'Solo Warm up',
            'Solo Warmup',
            'Solo warm up',
            '90 Day Solo Evaluation',
        ],
        'Stall Training': [
            'Steep Turns, Stalls, and Pattern work',
            'Taxi Takoff, Stalls, Manuvers',
            'Stall Training',
            'Stall lesson 1.4',
            'Stall lesson 1.5',
            'Stalls and Pattern work',
            'Stalls and Slow flight',
        ],
        'Pattern Work': [
            'Solo Pattern',
            'Communications, ADM, Patternwork',
            'Manuvers and Pattern work',
            'Night Operations, Pattern work',
            'Night Pattern work',
            'Pattern Work',
            'Troubleshoot and Pattern work',
            'Pattern work',
            'Pattern work / Flight review',
            'Pattern work / Trim Flight',
            'Pattern work and Steep Turns',
            'Pattern work and Visual attitude flight',
            'Pattern work and manuvers',
            'Pattern work crosswind Landings',
            'Pattern work part 3',
            'Pattern work part 4',
            'Pattern work part 4,5',
            'Pattern work part 5',
            'Pattern work part 6',
            'Pattern work, Engine out',
            'Pattern work, Forward Slip, Ground Referance',
            'Pattern work, Stalls, Emergency Decent',
            'Pattern work, Unusual attitudes',
            'Pattern wotk',
        ],
        'General Training': [
            'GPS',
            'GPS DP ILS',
            'GPS Holds ILS S/E',
            'GPS ILS',
            'GPS ILS LOC Hold S/E',
            'GPS ILS S/E  ',
            'GPS ILS S/E Hold',
            'GPS PP Hold',
            'GPS PP ILS',
            'GPS PP ILS S/E',
            'GPS, ILS S/E',
        ],
        'Multi Engine Training': [
            'MEI Prep',
            'MEL Holds ILS Approach',
            'MEL ILS,GPS, VOR, APP',
            'MEL Instrument Procedures',
            'MEL Manuvers',
            'Multi Engine Manuvers',
        ],
        'Checkrides': [
            'MEL Checkride Pass',
            'MEI Checkride - Pass',
            'COM SEL Checkride - Pass',
            'Commerical MEL Checkride - Pass',
            'CFI SEL Checkride - Pass',
            'Instrument Check Ride - Pass',
            'Private Pilot Check Ride - Pass',
            'Commerical Checkride prep',
            'COM SEL Checkride Prep',
            'CFII Checkride Pass',
            'CFII Checkride Prep',
            'Checkride retraining',
            'IFR Checkride Prep',
            'Instrument Checkride Prep',
            'Private Pilot Checkride Prep',
            'Private pilot checkride Prep',
            'Instrument Check Ride Prep',
            'Private Pilot Check Ride Prep',
        ],
        'Cross Wind Training': [
            'Cross wind Landings',
            'Cross wind Pattern',
            'Cross wind landings',
            'Crosswind Landing practice',
            'Crosswind Landings',
        ],
        'Emergency Training': [
            'Emergency Manuvers',
            'Emergency Landing Eval',
            'Emergency Landing Evaluation',
            'Emergency Landing evaluation',
            'Emergency Procedures',
            'Emergency Procedures Part 1',
            'Emergency Procedures Part 2',
            'Emergency Procedures and Pattern work',
            'Emergency landing eval',
            'Emergency procedures',
            'Emergency procedures Part 1',
            'Emergency procedures part 1',
            'Emergency procedures part 2',
        ],
        'Holds': [
            'Hold LDA, Instrument Attitude Flight',
            'Hold Procedures',
            'Hold Procedures LOC, LDA ',
            'Hold Procedures all entries',
            'Hold UTI, RNAV 1 KSGU, CTL',
            'Hold, LDA, LOC, DP',
            'Holding procedures LDA G/S',
            'Holds at UTI James Curtis Safty Pilot',
            'Holds, GPS, VOR approach',
            'Holds, VOR Approach',
            'Holds',
            'Holds / PP',
            'Holds All Entries',
            'Holds Direct Entry',
            'Holds LDA GS 19 KSGU',
            'Holds all entries LDA',
            'Holds, Attitude Instrument Flight',
            'Holds, LDA 19 KSGU PP',
            'Holds, LOC, LDA',
            'Holds, RNAV 01 KSGU CTL 19',
            'Holds, all entries',
        ],
        'IFR': [
            'IFR Curency / Bruce Roden Saftey Pilot',
            'IFR Currency Alvero Garcia Safty Pilot',
            'IFR Currency Hold UTI, RNAV, LDA 19 Alvero Garcia Safty Pilot',
            'IFR Currency Hold UTI, RNAV, LDA 19 Scott Stilson Safty Pilot',
            'IFR ACS',
            'IFR Communication RNAV 02 67L',
            'IFR Cross country',
            'IFR Cross country Training',
            'IFR Cross country training',
            'IFR Cross country training GPS 12R',
            'IFR Cross country training LDA 19',
            'IFR Cross country training VOR 20',
            'IFR Curency',
            'IFR Procedures ILS,RNAV cross country',
            'IFR Procedures cross country',
            'IFR TRaining',
            'IFR Traing',
            'IFR Training',
            'IFR Xcountry',
            'IFR training',
        ],
        'Slow Flight': [
            'Slow Flight and Stalls',
            'Slow flight and Stalls',
            'Slow flight and stalls',
            'Slow flight, Stalls,',
            'Slow flight, Stalls, Seep Turns and Landings',
        ],
        'Recreational Pilot': [
            'Recreational Pilot Manuvers',
            'Recreational Pilot PTS',
            'Reorentation Flight',
        ],
        'VOR': [
            'VOR Holds / Unusual Attitudes',
            'VOR KRAL, LOC KTOA, ILS KLGB',
            'VOR LOC/BC GPS',
            'VOR Approach, Attitude instrument flight',
            'VOR Approaches',
            'VOR B KPGA IFR Cross country Training',
            'VOR Holds',
            'VOR Intro',
            'VOR Navigation and Pattern work',
            'VOR Navigation and approaches',
            'VOR Track and Holds',
            'VOR Track, Heading, RNAV 19 KSGU',
            'VOR Tracking and Intercept',
            'VOR, ILS 20 KCDC',
        ],
        'RNAV': [
            'RNAV 01, IFR Communication',
            'RNAV 01, RNAV 19 KSGU',
            'RNAV 1 KSGU',
            'RNAV 1 KSGU IFR Cross country Training',
            'RNAV 12R ILS 12L KVGT',
            'RNAV 33 Instrument cross country Training',
        ],
        'Moving Aircraft': [
            'Move Aircraft To CA',
            'Move Aircraft to Las Vegas',
            'Move Aircraft to SGU',
            'Aircraft moved',
            'Return to Mesquite',
            'Aircraft returned from Maintance',
        ],
        'Maintance Flight': [
            'Maintaince Flight',
            'Maintance Flight',
            'Maintance Test Flight',
        ],
        'Other': [
            'Communication, stability',
            'Cowling Issue',
            'Currency Flight',
            'DME Arc MMM RNAV 1 KSGU',
            'DME Arc, ILS 20 KCDC',
            'DME Holds Airway, Intercept and Track',
            'DP LOC, LDA ',
            'DP RNAV 02, Published Missed, Hold, Arc ILS 20',
            'DP, GPS operation, Holds',
            'DP, RNAV 02',
            'Door open on takeoff',
            'Engine failure on Taxi',
            'Flat Tire on Taxi',
            'GPS Holds and gusty landing practice',
            'GPS LOC approaches',
            'Icing conditions after runup',
            'Landing Evaluation',
            'Landing Practice',
            'Local ATC',
            'Local senic flight',
            'Mag issue',
            'Navigation Training',
            'Non Precision approach procedures',
            'Nose Strut issue',
            'Oil pressure issue',
            'PA 24 Training',
            'PA 24 traing',
            'PA24 Training',
            'Power on/off stalls, soft/short field landings',
            'Pricision and Non Precision Approaches',
            'Procedure Turns, Arc,',
            'Proficency Flight',
            'Search for Hourse',
            'Run up failure',
            'Safty Pilot',
            'Ryan Grobe Safty Pilot',
            'Simulated Hood Time',
            'Simulated Instrument Training',
            'Stability and Landing practice',
            'Static Failure',
            'Tach Issue',
            'Test Flight',
            'Test flight',
            'Throttle issue on taxi',
            'Training',
            'Transport',
            'WINGS Flight A100126-54',
            'Weather issue during Taxi,',
            'C177 Time Build',
            'PA24 Time build',
            'ASI Failure',
            'ASI Test flight',
            'Auto Pilot Test',
            'Avonics work',
            'Avonics, AP C210 procedures',
            'Flight',
            'High Preformance Nav and Pattern work',
            'High preformance complex training',
            'Aircraft Issue',
            'Bartholomew Mag Issue',
            'Bring aircraft back to St George',
            'Camanchee Mag issue on runup',
            'Crew Procedures Training',
            'Landing Eval',
            'Landing Eval  ',
            'Landing Eval Prep',
            'Local Flight',
            'Local Solo',
            'Mag Issue',
            'Runup check issue',
            'Soft Field Landings',
            'Spin Training',
            'With Joseph',
            'Young Eagles',
        ],
    }
}